name: Test and Upload Python Package to Test PyPI

# Controls when the action will run.
on:
  push:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_dev_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest poetry typing-extensions

      - name: test with pytest
        run:
          pytest tests

      - name: Build wheels and source tarball
        run: |
          poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
          poetry version --short
          poetry build

      - name: publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN}}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true