# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        
    - name: Build wheels and source tarball
      run: >-
        poetry build

    - name: show temporary files
      run: >-
        ls -l

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
